themes:
  default:
    fg: 15
    bg: [40, 42, 54]
    black: 0
    blue: 6
    cyan: 14
    gray: 8
    green: 2
    magenta: 5
    orange: 3
    red: 1
    white: 15
    yellow: 3

# https://mzte.de/git/lordmzte/zellij-compact-status
plugins:
  - path: compact-status.wasm
    tag: compact-status

default_shell: fish
