idle_bg = "#44475a"
idle_fg = "#f8f8f2"
info_bg = "#44475a"
info_fg = "#f8f8f2"
good_bg = "#50fa7b"
good_fg = "#6272a4"
warning_bg = "#ffb86c"
warning_fg = "#bd93f9"
critical_bg = "#ff5555"
critical_fg = "#bd93f9"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
