[package]
name = "i3man"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
i3_ipc = "0.14.0"
tracing = "0.1.32"
tracing-subscriber = "0.3.9"
