[package]
name = "randomwallpaper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
rand = "0.8.5"
walkdir = "2.3.2"
x11 = { version = "2.19.1", features = ["xinerama", "xlib"] }
