# This file creates aliases of normal GNU coreutils to their UUtils version if installed.

if not which "uu-cat" > /dev/null
    exit
end

function uualias
    set -l cmd "$argv[1]"
    alias "$cmd"=uu-"$cmd"
end

uualias arch
uualias base32
uualias base64
uualias basename
uualias basenc
uualias cat
uualias chgrp
uualias chmod
uualias chown
uualias chroot
uualias cksum
uualias comm
uualias coreutils
uualias cp
uualias csplit
uualias cut
uualias date
uualias dd
uualias df
uualias dircolors
uualias dirname
uualias du
uualias echo
uualias env
uualias expand
uualias expr
uualias factor
uualias false
uualias fmt
uualias fold
uualias groups
uualias hashsum
uualias head
uualias hostid
uualias hostname
uualias id
uualias install
uualias join
uualias kill
uualias link
uualias ln
uualias logname
uualias ls
uualias mkdir
uualias mkfifo
uualias mknod
uualias mktemp
uualias more
uualias mv
uualias nice
uualias nl
uualias nohup
uualias nproc
uualias numfmt
uualias od
uualias paste
uualias pathchk
uualias pinky
uualias pr
uualias printenv
uualias printf
uualias ptx
uualias pwd
uualias readlink
uualias realpath
uualias relpath
uualias rm
uualias rmdir
uualias seq
uualias shred
uualias shuf
uualias sleep
uualias sort
uualias split
uualias stat
uualias stdbuf
uualias sum
uualias sync
uualias tac
uualias tail
uualias tee
uualias timeout
uualias touch
uualias tr
uualias true
uualias truncate
uualias tsort
uualias tty
uualias uname
uualias unexpand
uualias uniq
uualias unlink
uualias uptime
uualias users
uualias wc
uualias who
uualias whoami
uualias yes
