[theme]
theme = "dracula"

[icons]
icons = "material-nf"

[icons.overrides]
# this should never show, as the bat block auto hides without a battery
bat_not_available = "x"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "$mem_used_percents $mem_used/$mem_avail"
format_swap = "$swap_used_percents $swap_used/$swap_free"

[[block]]
block = "cpu"
interval = 1
format = "$frequency $barchart $utilization"

[[block]]
block = "temperature"
collapsed = false
interval = 5
format = "$min - $average ~ $max +"
chip = "*-isa-*"
idle = 50
info = 70
warning = 85

[[block]]
block = "music"
interface_name_exclude = [".*kdeconnect.*", "mpd"]
hide_when_empty = true
format = "{$combo.rot-str(20, 0.1)|} $prev $play $next"

[[block]]
block = "sound"
format = "$output_description{ $volume|}"

[[block]]
block = "battery"
interval = 10
format = "$percentage $power"
hide_missing = true

[[block]]
block = "time"
interval = 1
format = "%a %d.%m.%Y %T"
