#!/bin/sh

# play a twitch stream using streamlink

__usage="
USAGE:
    $0 <stream_name> [quality]

ARGS:
    <stream_name>   Name of the stream to play
    [quality]       quality to use [default: best]
"

if [ -z $1 ] || [ $# -gt 2 ] || [ $1 = "--help" ]; then
    echo -e "$__usage"
else
    streamlink https://twitch.tv/$1 ${2:-best}
fi
